### ISSUE TITLE
Spring loaded is in the attic

### ISSUE THREAD

**Issue by fletchgqc** [spring-projects/spring-loaded#169]
On this page https://spring.io/projects Spring Loaded is listed as being "in the attic". Can anyone explain what that means? It implies "abandoned" to me, which is reflected by the commit activity here. If so, is there anywhere where the reason for this is explained or where a replacement tool is recommended?

**Comment by aclement** [comment]
Hey. There are two challenges when performing this style of reloading. The first is to actually achieve the bytecode reload, which SpringLoaded does quite well. The second challenge is the ecosystem around plugins for libraries. Just because a type has been reloaded doesn't mean every library out there can deal with it - many of them will be doing things like caching the result of reflective calls because they don't realize that with agent based reloading in the mix those results can change. So for each library you need a plugin. These plugins may need to poke into internals where these caches are held, thus they can be brittle and the maintenance effort shouldn't be underestimated.

For Spring Boot 1.3 we looked at a more basic form of reloading that did not require this level of maintenance and the result was Spring Boot Dev Tools which is discussed in this blog article: https://spring.io/blog/2015/06/17/devtools-in-spring-boot-1-3 . This isn't as fast as agent based reloading but is much quicker than a full cold restart.  If you need the instant reloading perhaps you should consider JRebel.

That being said, Grails is using SpringLoaded and the maintenance on this project has been around fixing bugs in that Grails usage, which seems to have many fewer requirements on this third party library support because of how they do things. I expect that to continue.

**Comment by fletchgqc** [comment]
Thanks. This fully answers my question.

**Comment by werpu** [comment]
Ok this is unfortunate news, I am one of the devs for whom springloaded really works well, and I had my fair share of problems with JRebel in the past on the same codebase (that and their insane price hikes they performed after they basically expired their lifetime licenses). 

This is bad news indeed. The spring dev tools approach unfortunately is subpar to spring loaded in my situation since lots of init code depends in my application on the application context startup. And restructuring that so that it works well with the dev tools means loads of work. (also even if we restructure it would mean a lot of performance loss on out side for the roundtripping)

I hope you guys one day might reconsider your stance. I´d rather have a well working 99% solution 
 than a slow 100% solution which needs lots of rework. In the meanwhile. Thanks for all the good work on this project it will continue to save us a lot of time until it wont work anymore with whatever spring and java version might break it.
