### ISSUE TITLE
when using with spring-boot, throws an error.

### ISSUE THREAD

**Issue by mihayinoviki** [spring-projects/spring-loaded#197]
when someone changed, Spring Loaded throws "Unable to find regeneration methods for cglib proxies - proxies will be out of date for this type" and "Spring Loaded: Cannot reload new version of com.sun.proxy.$Proxy"

**Comment by lmx1989219** [comment]
+1

**Comment by gokhansari** [comment]
+1

**Comment by highdali** [comment]
+1

**Comment by ronlv10** [comment]
+1

**Comment by suiwenfeng** [comment]
+1

**Comment by brianthi** [comment]
+1

**Comment by chauzer** [comment]
+1

**Comment by agnadesai** [comment]
+1

**Comment by quangthe** [comment]
+1

**Comment by aclement** [comment]
I don't get a lot of time to look at this project, but when I do having accurate instructions to recreate the problem helps immensely. Anyone got a test project?

**Comment by agnadesai** [comment]
I created example project here or see attached project. https://github.com/agnadesai/springLoadedWithSpringBoot look forward to a solution to this problem. You can thank me for working on a day before thanksgiving later. :)
[SpringBootApp.zip](https://github.com/spring-projects/spring-loaded/files/1497452/SpringBootApp.zip)

**Comment by aclement** [comment]
Thanks for the sample.I fixed the problem of the "Unable to find regeneration methods for cglib proxies - proxies will be out of date for this type" message it reproduced for me.  This was due to changes in the cglib code.  We try to intercept the calls made from the AbstractClassGenerator.create() method to the 'generate' method.  Then when a type changes we re-drive that generate.  In newer cglib the generate call is not made from the create so we weren't catching it for later invocation.  I've adjusted it to do something different that will catch generate in the new code.  I also enhanced the messages a little more to indicate which types it is having trouble with.  Now, when i follow the instructions in the attached app, it shows:

 [Loader@18b4aac2] org.springsource.loaded.ReloadableType   : Attempting reload of cglib proxy for type com/myproject/Application
[Loader@18b4aac2] o.s.l.a.ClassPreProcessorAgentAdapter    : > (loader=sun.misc.Launcher$AppClassLoader@18b4aac2 className=org/springsource/loaded/ri/ReloadedTypeInvoker, classBeingRedefined=null, protectedDomain=true, bytes= 4715
[Loader@18b4aac2] o.s.l.agent.SpringLoadedPreProcessor     : SpringLoaded preprocessing: classname=org/springsource/loaded/ri/ReloadedTypeInvoker classloader=Launcher$AppClassLoader typeRegistry=TypeRegistry(id=250421012,loader=sun.misc.Launcher$AppClassLoader)
[Loader@18b4aac2] o.s.l.a.ClassPreProcessorAgentAdapter    : > (loader=sun.misc.Launcher$AppClassLoader@18b4aac2 className=org/springsource/loaded/ri/ReloadedTypeInvoker$1, classBeingRedefined=null, protectedDomain=true, bytes= 1935
[Loader@18b4aac2] o.s.l.agent.SpringLoadedPreProcessor     : SpringLoaded preprocessing: classname=org/springsource/loaded/ri/ReloadedTypeInvoker$1 classloader=Launcher$AppClassLoader typeRegistry=TypeRegistry(id=250421012,loader=sun.misc.Launcher$AppClassLoader)
[Loader@18b4aac2] org.springsource.loaded.ReloadableType   : Proxy regenerate successful for com/myproject/Application

1.2.9.BUILD-SNAPSHOT on repo.spring.io should contain the change.

**Comment by aclement** [comment]
The cglib proxy generation is not the reason that request mappings don't reload - so fixing that error doesn't make request mappings reload in your app.  So I have also, just now,  updated the SpringPlugin so you can reload request mappings - at least in the spring 4.3.12 your app uses it works fine now. Possibly works in spring 5 but I haven't checked if they modified the structure again.
